# Generated by Django 5.0.7 on 2024-08-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('bid_description', models.CharField(max_length=2000)),
                ('start_price', models.IntegerField(default=0)),
                ('sold_price', models.IntegerField(default=0, editable=False)),
                ('bidders', models.ManyToManyField(to='Auction.user')),
                ('bought_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_curr_owner', to='Auction.user')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_last_owner', to='Auction.user')),
            ],
        ),
    ]
